---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box

suites:
- name: scribe-endpoint
  run_list: ["recipe[scribe::endpoint]", "recipe[minitest-handler]"]
  attributes: {}
- name: scribe-relay
  run_list: ["recipe[scribe::relay]", "recipe[minitest-handler]"]
  attributes: {"scribe":{"remote_host":"127.1.2.3"}}
